/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExercisesExerciseIdRouteImport } from './routes/exercises.$exerciseId'
import { Route as ExercisesSplatRouteImport } from './routes/exercises.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesExerciseIdRoute = ExercisesExerciseIdRouteImport.update({
  id: '/exercises/$exerciseId',
  path: '/exercises/$exerciseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesSplatRoute = ExercisesSplatRouteImport.update({
  id: '/exercises/$',
  path: '/exercises/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercises/$': typeof ExercisesSplatRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercises/$': typeof ExercisesSplatRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercises/$': typeof ExercisesSplatRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exercises/$' | '/exercises/$exerciseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exercises/$' | '/exercises/$exerciseId'
  id: '__root__' | '/' | '/exercises/$' | '/exercises/$exerciseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExercisesSplatRoute: typeof ExercisesSplatRoute
  ExercisesExerciseIdRoute: typeof ExercisesExerciseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$exerciseId': {
      id: '/exercises/$exerciseId'
      path: '/exercises/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof ExercisesExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$': {
      id: '/exercises/$'
      path: '/exercises/$'
      fullPath: '/exercises/$'
      preLoaderRoute: typeof ExercisesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExercisesSplatRoute: ExercisesSplatRoute,
  ExercisesExerciseIdRoute: ExercisesExerciseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
